myapp/urls.py
from django import urls
from django.urls import path

from .views import  DeleteUserView, HomePageView,AddUserView ,DetailPageView, UpdateUserView

app_name = 'myapp'

urlpatterns = [
     path('',HomePageView.as_view(),name="index"),
     path('detail/<str:pk>',DetailPageView.as_view(),name="detail"),
     path('add/',AddUserView.as_view(),name="add"),
     # path('delete-img/<str:pk>', deleteImage,name="delete-img"),
     path('delete/<int:id>', DeleteUserView.as_view(),name='delete'),
     path('update/<str:pk>', UpdateUserView.as_view(),name='update'),
  
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include

from myapp import urls as myapp_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(myapp_urls, namespace='myapp')),
   
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from typing import Text
from django.db import models
from django.db.models.fields import EmailField, IntegerField, TextField
from sorl.thumbnail import ImageField


# Create your models here.

class UserDetail(models.Model):
    name =  models.CharField(max_length=155,null=False,blank=False)
    age = IntegerField(blank=False,null=False)
    email = EmailField(max_length=155,blank=False,null=False)
    place = models.CharField(max_length=155,null=False,blank=False)
    occupation = models.CharField(max_length=155,null=False,blank=False)
    gender = models.CharField(max_length=155,null=False,blank=False)
    image = ImageField()


    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('detail')

myapp/forms.py
from django import forms
from .models import UserDetail
class UserForm(forms.ModelForm):
    class Meta:
        model = UserDetail
        # name = forms.CharField()
        # image = forms.FileField()
        # age = forms.IntegerField()
        # email = forms.EmailField()
        # place = forms.CharField()
        # occupation = forms.CharField()
        fields = ('name', 'image', 'age', 'email', 'place', 'occupation','gender')

        widgets={
            'name' : forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}),
            'image' : forms.FileInput(attrs={'class':'form-control','placeholder':'Image Url'}),
            'age' : forms.NumberInput(attrs={'class':'form-control','placeholder':'Age'}),
            'email' : forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}),
            'place' : forms.TextInput(attrs={'class':'form-control','placeholder':'Place'}),
            'occupation' : forms.TextInput(attrs={'class':'form-control','placeholder':'Occupation'}),
            'gender' : forms.TextInput(attrs={'class':'form-control','placeholder':'Gender'}),

        }
    

    
    

myapp/views.py
from django.contrib import messages
from django.contrib.messages.constants import SUCCESS
from django.http import request
from django.shortcuts import  get_object_or_404, redirect
from django.views.generic import TemplateView, DetailView, FormView, DeleteView, UpdateView
from .forms import UserForm

from .models import UserDetail
from .forms import UserForm
# Create your views here.

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['user_detail'] = UserDetail.objects.all()
        return context

class DetailPageView(DetailView):
    template_name = "detail.html"
    model = UserDetail

class AddUserView(FormView):
    template_name = "adduser.html"
    form_class = UserForm
    success_url = "/"
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request,*args,**kwargs)
    def form_valid(self, form):
        # Create a new User Data
        new_object = UserDetail.objects.create(
            name = form.cleaned_data['name'],
            image = form.cleaned_data['image'],
            email = form.cleaned_data['email'],
            age = form.cleaned_data['age'],
            place = form.cleaned_data['place'],
            occupation = form.cleaned_data['occupation'],
            gender = form.cleaned_data['gender'],
         
        )
        messages.add_message(self.request ,messages.SUCCESS,'User Details Added Successfully')
        return super().form_valid(form)

class UpdateUserView(UpdateView):
    template_name = "update.html"
    model = UserDetail
    form_class = UserForm
    success_url = "/"
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request,*args,**kwargs)

    def form_valid(self, form):
        messages.add_message(self.request ,messages.SUCCESS,'User Details Updated Successfully')
        return super().form_valid(form)
        
    # fields = ['name','image','age','email','place','occupation']

class DeleteUserView(DeleteView):
    template_name = "delete.html"
    form_class = UserForm
    success_url = "/"
    model = UserDetail

    def dispatch(self, request, *args, **kwargs):
        # self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        id_ = self.kwargs.get("id")
      
        return get_object_or_404(UserDetail,id=id_)
    def post(self, request, *args, **kwargs):
          self.request = request
          messages.add_message(self.request,messages.SUCCESS,"Successfully Deleted User Details")
          return self.delete(request, *args, **kwargs)
        







 

  

templates/addUser.html
{% extends 'base.html' %}

{% block title %}
    Add New User Details
{% endblock title %}

{% block body %}
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
<div class="container rounded-3 my-5 bgcontainer p-5 shadow  box w-50">
    <h2 class="fw-semi-bold my-3 pb-1" id="profileh3">User Profile</h2>
    <div class="my-3">
        {{form.as_table}}
    </table>
    </div>
    <div>
        <button class="btn btn-outline-dark" type="submit">Add User</button>
    </div>
</div>

</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Image Sharer
        {% endblock  %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    {% include 'includes/navbar.html' %}
{% if messages %}
{% for message in messages %}
<div class="bg-{% if message.tags %}{{ message.tags }}{% else %}Success{% endif %} bg-gradient text-center text-white py-1">
    {{ message }}
    </div>
    {% endfor %}
{% endif %}




    {% block body%}{% endblock%}
</body>

</html>

templates/delete.html
{% extends 'base.html' %}


{% block title %}
    Delete Conformation
{% endblock title %} 

{% block body %}
<div class="container offset-sm-1 my-3">
  <h1>{{ object.name }}</h1>
  <form method="POST" action="" >
  {% csrf_token %}    
      <div>
      <p class="fs-3">Are you sure to delete {{ object.name }} details?</p>
      <p> <input class="px-3 btn btn-danger" type="submit" value='Yes'/>
      <a class="btn btn-outline-dark" href="../">Cancel</a></p>     
  </div>
  </form>
</div>



{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block title %}
DetailUserView
{% endblock title %}
DetailUserView

{% block  body %}
<body class="background">
    <div class="container rounded-3 my-5 bgcontainer  shadow  box">
        <div class="row">
            <div class="col-md-4">
                <div class="
                  d-flex
                  align-items-stretch
                  flex-column
                  h-75
                  <!-- h-50 -->
                  justify-content-center
                  ">
                    <div class="row mt-md-5">
                        <div class="col text-center">
                            <img class="rounded-circle mb-3" id="imgload" src='{{ object.image.url }}' width="175px"
                                height="175px" alt="" />
                            <h5 class="myname">{{ object.name }}</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-center">
                            <small>
                                <p class="idinfo fs-6 text-light" aria-placeholder="Idinfo">User Link</p>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-7 px-0 mt-md-3">
                <h2 class="fw-semi-bold my-3 pb-1" id="profileh3">{{object.name}} Profile</h2>
                <div class="container border mt-4 ">
                    <div class="row mt-5 mb-3">
                        <div class="col-7">
                            <label class="fs-4" for="name">UserName</label>
                            <input class=" w-100 form-control shadow" type="text" name="name" id="name"
                                placeholder="UserName" aria-label="Name" value="{{ object.name }}"disabled />
                        </div>
                        <div class="col-3">
                            <label class="fs-4 for="id">UserID</label>
                            <input class=" w-70 form-control" type="text" name="id" id="id" placeholder="UserID"
                                value="{{ object.id }}" disabled />
                        </div>
                    </div>
                    <div class="row mb-4 mb-4">
                        <div class="col-12">
                            <label class="fs-4" for="gender">Gender</label>
                            <input class=" w-100 form-control" type="text" name="gender" id="gender"
                                placeholder="Gender" value="{{ object.gender }}" disabled/>
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-5">
                            <label class="fs-4" for="hairColor">Age</label>
                            <input class="w-100 form-control" type="Age" name="name" id="age" placeholder="Age"
                                value="{{ object.age }}" disabled/>
                        </div>
                        <div class="col-7">
                            <label class="fs-4 for="eyeColor">Email</label>
                            <input class="w-100 form-control" type="eyeColor" name="email" id="email"
                                placeholder="Email" value="{{ object.email }}" disabled/>
                        </div>
                    </div>

                    <div class="row mb-4">
                        <div class="col-12">
                            <label class="fs-4 for="occupation">Occupation</label>
                            <input class=" w-100 form-control" type="text" name="occupation" id="occupation"
                                placeholder="Occupation" value="{{ object.occupation }}"disabled />
                        </div>
                    </div>
                    <div class="row mb-4">
                        <div class="col-7">
                            <label class="fs-4 for="Place">Place</label>
                            <input class="w-100 form-control" type="Place" name="Place" id="Place" placeholder="Place"
                                value="{{ object.place }}" disabled/>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row mb-4">
                <div class="col-12">
                    <div class="flex text-center mt-4">
                        <a href="{% url 'myapp:update' object.id%}" class="btn btn-outline-success shadow">Update</a>
                        <a href="{% url 'myapp:delete' object.id%}" class="btn btn-danger">Delete</a>

                    </div>
                </div>
            </div>
            <!-- <div class="col-3">dfds</div> -->
        </div>
    </div>



    {% endblock  %}

templates/home.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Home Template
{% endblock title %}

{% block body%}
<div class="row">
    {% for details in user_detail %}
          <div class="col-sm-6 col-md-2 mx-3 mt-5">
            <div class="card" style="width: 100%;">

                  <img class="rounded-circle  align-self-center mt-3" src="{{ details.image.url }}" width="135px" height="155px" alt="...">    

              <div class="card-body">
                <h6 class="card-title text-center">{{ details.name }}</h6>
                <div class="w-auto text-center"><small></small><a href="{% url 'myapp:detail' details.id %}"class="btn btn-outline-dark align-item-center">View Profile</a></div>
              
              </div>
            </div> 
          </div>
        <!-- <img src='{{ details.image.url }}' /> -->
        <!-- <hr> -->
    {% endfor %}
    {% comment %} <h1>{{ user_detail }}</h1> {% endcomment %}
    </div>
    {% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">User Details</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
          <a class="nav-link" href="{% url 'myapp:add' %}">Add User</a>
      
        </div>
      </div>
    </div>
  </nav>

templates/update.html
{% extends 'base.html' %}

{% block title %}
    Update User Details
{% endblock title %}

{% block body %}
<form class="mt-5" method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
<div class="container rounded-3 my-5 bgcontainer p-5 shadow  box w-50">
<table class="offset-2">
    <div class="d-flex">
        <div class=" text-center offset-2">
            <img class=" mb-3 " src={{object.image.url}} id="imgload" src='' width="175px"
                height="175px" alt="" />
        </div>
        <div class="d-flex">
            {{ form.as_table }}
        </div>   
    </div>
</table>

<div class="w-100 offset-2" >
    <button class="btn btn-success m-5" type="submit">Update User</button>
</div>
</div>
</form>
{% endblock %}